/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import org.example.model.PlayerModel;
import org.example.service.PlayerService;

import javax.swing.*;
import java.sql.SQLException;
import java.util.List;

/**
 * @author Ngọc Viên
 */
public class RankingFrame extends javax.swing.JFrame {

    /**
     * Creates new form RankingFrame
     */
    public RankingFrame() {
        initComponents();
        evenhandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreTop1 = new javax.swing.JLabel();
        usernameTop1 = new javax.swing.JLabel();
        scoreTop2 = new javax.swing.JLabel();
        usernameTop2 = new javax.swing.JLabel();
        usernameTop3 = new javax.swing.JLabel();
        scoreTop3 = new javax.swing.JLabel();
        usernameTop4 = new javax.swing.JLabel();
        scoreTop4 = new javax.swing.JLabel();
        usernameTop5 = new javax.swing.JLabel();
        scoreTop5 = new javax.swing.JLabel();
        usernameTop6 = new javax.swing.JLabel();
        scoreTop6 = new javax.swing.JLabel();
        usernameTop7 = new javax.swing.JLabel();
        scoreTop7 = new javax.swing.JLabel();
        usernameTop8 = new javax.swing.JLabel();
        scoreTop8 = new javax.swing.JLabel();
        usernameTop9 = new javax.swing.JLabel();
        scoreTop9 = new javax.swing.JLabel();
        usernameTop10 = new javax.swing.JLabel();
        scoreTop10 = new javax.swing.JLabel();
        avatarLabel3 = new javax.swing.JLabel();
        avatarLabel2 = new javax.swing.JLabel();
        avatarLabel1 = new javax.swing.JLabel();
        avatarLabel4 = new javax.swing.JLabel();
        avatarLabel5 = new javax.swing.JLabel();
        avatarLabel6 = new javax.swing.JLabel();
        avatarLabel7 = new javax.swing.JLabel();
        avatarLabel8 = new javax.swing.JLabel();
        avatarLabel9 = new javax.swing.JLabel();
        avatarLabel10 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scoreTop1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop1.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 75, 110, 40));

        usernameTop1.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop1.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, 120, 40));

        scoreTop2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop2.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, 40));

        usernameTop2.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop2.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 40));

        usernameTop3.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop3.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 165, 140, 40));

        scoreTop3.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop3.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 165, 110, 40));

        usernameTop4.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop4.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 204, 140, 40));

        scoreTop4.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop4.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 204, 110, 40));

        usernameTop5.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop5.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 247, 140, 40));

        scoreTop5.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop5.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 247, 90, 40));

        usernameTop6.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop6.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 140, 40));

        scoreTop6.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop6.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 90, 40));

        usernameTop7.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop7.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 337, 140, 40));

        scoreTop7.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop7.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 337, 90, 40));

        usernameTop8.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop8.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 140, 40));

        scoreTop8.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop8.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 90, 40));

        usernameTop9.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop9.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 424, 140, 40));

        scoreTop9.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop9.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 424, 90, 40));

        usernameTop10.setFont(new java.awt.Font("Dubai Medium", 1, 20)); // NOI18N
        usernameTop10.setForeground(new java.awt.Color(255, 255, 255));
        usernameTop10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usernameTop10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 465, 140, 40));

        scoreTop10.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        scoreTop10.setForeground(new java.awt.Color(255, 255, 255));
        scoreTop10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(scoreTop10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 465, 90, 40));
        getContentPane().add(avatarLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 170, -1, -1));
        getContentPane().add(avatarLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 125, -1, -1));
        getContentPane().add(avatarLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 80, -1, -1));
        getContentPane().add(avatarLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 210, -1, -1));
        getContentPane().add(avatarLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 253, -1, -1));
        getContentPane().add(avatarLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 296, -1, -1));
        getContentPane().add(avatarLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 340, -1, -1));
        getContentPane().add(avatarLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 383, -1, -1));
        getContentPane().add(avatarLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 430, -1, -1));
        getContentPane().add(avatarLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 472, -1, -1));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/top10.png"))); // NOI18N
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RankingFrame().setVisible(true);
//            }
//        });
//    }
    public static void display() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingFrame().setVisible(true);
            }
        });
    }

    private void evenhandler() {
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        playerService = new PlayerService();
        usernameLabels = new JLabel[]{usernameTop1, usernameTop2, usernameTop3,
                usernameTop4, usernameTop5, usernameTop6, usernameTop7, usernameTop8, usernameTop9, usernameTop10};
        scoreLabels = new JLabel[]{scoreTop1, scoreTop2, scoreTop3, scoreTop4, scoreTop5, scoreTop6, scoreTop7,
                scoreTop8, scoreTop9, scoreTop10};
        avatarLabels=new JLabel[]{avatarLabel1, avatarLabel2, avatarLabel3, avatarLabel4,avatarLabel5,avatarLabel6,
        avatarLabel7, avatarLabel8, avatarLabel9, avatarLabel10};
        try {
            top10=playerService.getRankingTop10();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        int index=0;
        for(PlayerModel player:top10) {
            usernameLabels[index].setText(player.getUsername());
            scoreLabels[index].setText(player.getRankScore()+"");
            String avatarPath = player.getAvatarPath();
            System.out.println(avatarPath);
            java.net.URL imgUrl = null;
            if (avatarPath != null && !avatarPath.isEmpty()) {
                imgUrl = getClass().getResource("/avatar/" + avatarPath + ".png");
            }
            if (imgUrl != null) {
                avatarLabels[index].setIcon(new ImageIcon(imgUrl));
            } else {
                avatarLabels[index].setIcon(new ImageIcon(getClass().getResource("/avatar/default.png")));
            }
            index++;
        }

    }

    private PlayerService playerService;
    private List<PlayerModel> top10;
    private JLabel[] avatarLabels;
    private JLabel[] usernameLabels;
    private JLabel[] scoreLabels;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLabel1;
    private javax.swing.JLabel avatarLabel10;
    private javax.swing.JLabel avatarLabel2;
    private javax.swing.JLabel avatarLabel3;
    private javax.swing.JLabel avatarLabel4;
    private javax.swing.JLabel avatarLabel5;
    private javax.swing.JLabel avatarLabel6;
    private javax.swing.JLabel avatarLabel7;
    private javax.swing.JLabel avatarLabel8;
    private javax.swing.JLabel avatarLabel9;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel scoreTop1;
    private javax.swing.JLabel scoreTop10;
    private javax.swing.JLabel scoreTop2;
    private javax.swing.JLabel scoreTop3;
    private javax.swing.JLabel scoreTop4;
    private javax.swing.JLabel scoreTop5;
    private javax.swing.JLabel scoreTop6;
    private javax.swing.JLabel scoreTop7;
    private javax.swing.JLabel scoreTop8;
    private javax.swing.JLabel scoreTop9;
    private javax.swing.JLabel usernameTop1;
    private javax.swing.JLabel usernameTop10;
    private javax.swing.JLabel usernameTop2;
    private javax.swing.JLabel usernameTop3;
    private javax.swing.JLabel usernameTop4;
    private javax.swing.JLabel usernameTop5;
    private javax.swing.JLabel usernameTop6;
    private javax.swing.JLabel usernameTop7;
    private javax.swing.JLabel usernameTop8;
    private javax.swing.JLabel usernameTop9;
    // End of variables declaration//GEN-END:variables
}
