/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import org.example.model.PlayAudioURL;
import org.example.model.PlayerModel;
import org.example.service.AuthService;
import org.example.service.PlayerService;

import javax.sound.sampled.Clip;
import javax.swing.*;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Ngọc Viên
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        playerService = new PlayerService();
        authService = new AuthService();
        initComponents();
//        clipStart = PlayAudio.playStartAudio("src/main/java/org/example/file/audio/" +
//                "nhạc-bắt-đầu-chương-trình-ALTP-_2008-2020_.wav", -10);
        ImageIcon icon = new ImageIcon(getClass().getResource("/elements/AiLaTrieuPhu.png"));
        setIconImage(icon.getImage());
        evenHandler();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButon = new javax.swing.JButton();
        loginRectangle = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        submitButon = new javax.swing.JButton();
        usernameFieldLabel = new javax.swing.JLabel();
        playRectangle = new javax.swing.JLabel();
        passwordFieldLabel = new javax.swing.JLabel();
        aiLaTrieuPhuLable = new javax.swing.JLabel();
        welcomeBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        qrCodeItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButon.setBackground(new java.awt.Color(0, 42, 93));
        loginButon.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        loginButon.setForeground(new java.awt.Color(255, 255, 255));
        loginButon.setText("Login");
        loginButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 315, 105, 24));

        loginRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Rectangle 2.png"))); // NOI18N
        getContentPane().add(loginRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 312, -1, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 228, 141, 25));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 188, 141, 25));

        usernameLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 192, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 232, -1, -1));

        submitButon.setBackground(new java.awt.Color(0, 42, 93));
        submitButon.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        submitButon.setForeground(new java.awt.Color(255, 255, 255));
        submitButon.setText("Sign Up");
        getContentPane().add(submitButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 270, 128, -1));

        usernameFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Username field.png"))); // NOI18N
        getContentPane().add(usernameFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 184, -1, -1));

        playRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Rectangle 4.png"))); // NOI18N
        getContentPane().add(playRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 266, -1, -1));

        passwordFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Username field.png"))); // NOI18N
        getContentPane().add(passwordFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 224, -1, -1));

        aiLaTrieuPhuLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/AiLaTrieuPhu.png"))); // NOI18N
        getContentPane().add(aiLaTrieuPhuLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -20, -1, 260));

        welcomeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/login-bg.png"))); // NOI18N
        getContentPane().add(welcomeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("File");

        qrCodeItem.setText("bổ sung câu hỏi");
        qrCodeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrCodeItemActionPerformed(evt);
            }
        });
        jMenu1.add(qrCodeItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButonActionPerformed

    private void qrCodeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrCodeItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qrCodeItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    private void evenHandler() {

        setLocationRelativeTo(null);
        setDocumentFilter(passwordField,15);
        getRootPane().setDefaultButton(submitButon);
//        setLocation(420, 250);

//        PlayAudio.playAudio("C:\\Users\\admin\\IdeaProjects\\AiLaTrieuPhu\\" +
//                "src\\main\\java\\org\\example\\file\\audio\\funky-and-jazzy-gang-loop-251858.wav",-10);
        // Sử dụng JButton thông thường và thay đổi con trỏ chuột
        submitButon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        loginButon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));


        submitButon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-3-269281.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-3-269281.wav"));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {

//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-off-269284.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-off-269284.wav"));
            }
        });
        loginButon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-3-269281.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-3-269281.wav"));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {

                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-off-269284.wav"));
            }
        });

        loginButon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                WelcomeFrame.display();
            }
        });
        submitButon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (passwordField.getText().isEmpty() || usernameField.getText().isEmpty()) {
                    PlayAudioURL.wrongSound();
                    JOptionPane.showMessageDialog(null, "Nhập đầy đủ username và password!");
                }
                else if(usernameField.getText().contains(" ")){
                    PlayAudioURL.wrongSound();
                    JOptionPane.showMessageDialog(null, "Username không được chứa dấu cách!");
                }
                else if(passwordField.getText().length()<6){
                    PlayAudioURL.wrongSound();
                    JOptionPane.showMessageDialog(null, "Password phải có ít nhất 6 ký tự");
                }
                else {
                    username = usernameField.getText();
                    password = passwordField.getText();
                    try {
                        isSignUp = authService.register(username, password);
                    } catch (Exception ex) {
                        throw new RuntimeException(ex);
                    }
                    if (isSignUp) {
                        JOptionPane.showMessageDialog(null, "Đăng ký tài khoảng thành công");
                        PlayAudioURL.playAudio(getClass().getResource("/audio/level-up-2-199574_1.wav"));
                        WelcomeFrame.display();
                        dispose();
                    }else {
                        JOptionPane.showMessageDialog(null, "Đăng ký tài khoảng thất bại");
                    }

                }
            }
        });

        qrCodeItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null,"",
                        "Vào link để thêm câu hỏi",
                        JOptionPane.INFORMATION_MESSAGE,
//                        new ImageIcon("src/main/resources/elements/QRcode-ggSheets.png")
                        new ImageIcon(getClass().getResource("/elements/QRcode-ggSheets.png"))
                );
            }
        });

    }

    static void makeButtonTransparent(JButton button) {
        button.setContentAreaFilled(false);
        button.setOpaque(false);
    }

    public static void setDocumentFilter(JTextField textField, int maxLength) {
        PlainDocument doc = new PlainDocument();
        doc.setDocumentFilter(new javax.swing.text.DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (fb.getDocument().getLength() + string.length() <= maxLength) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (fb.getDocument().getLength() - length + text.length() <= maxLength) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
        textField.setDocument(doc);
    }

    private boolean isSignUp;
    private AuthService authService;
    private String username;
    private String password;
    private PlayerModel player;
    private PlayerService playerService;
    private Clip clipStart;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiLaTrieuPhuLable;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton loginButon;
    private javax.swing.JLabel loginRectangle;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordFieldLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel playRectangle;
    private javax.swing.JMenuItem qrCodeItem;
    private javax.swing.JButton submitButon;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameFieldLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeBackground;
    // End of variables declaration//GEN-END:variables
}
