/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view;

import javazoom.jl.player.Player;
import org.example.model.PlayAudio;
import org.example.model.PlayAudioURL;
import org.example.model.PlayerModel;
import org.example.service.AuthService;
import org.example.service.PlayerService;

import javax.sound.sampled.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 * @author Ngọc Viên assets
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        playerService = new PlayerService();
        authService = new AuthService();
        initComponents();
//        clipStart = PlayAudio.playStartAudio("src/main/java/org/example/file/audio/" +
//                "nhạc-bắt-đầu-chương-trình-ALTP-_2008-2020_.wav", -10);
        ImageIcon icon = new ImageIcon(getClass().getResource("/elements/AiLaTrieuPhu.png"));
        setIconImage(icon.getImage());
        clipStart = PlayAudioURL.playStartAudio(getClass().getResource("/audio/nhạc-bắt-đầu-chương-trình-ALTP-_2008-2020_.wav"),-10);
        evenHandler();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rankingButon = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameFieldLabel = new javax.swing.JLabel();
        rankingLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        passwordFieldLabel = new javax.swing.JLabel();
        signUpButon = new javax.swing.JButton();
        playButon = new javax.swing.JButton();
        playRectangle = new javax.swing.JLabel();
        quitRectangle = new javax.swing.JLabel();
        aiLaTrieuPhuLable = new javax.swing.JLabel();
        welcomeBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        qrCodeItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(rankingButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 188, 141, 25));

        usernameLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 192, -1, -1));

        usernameFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Username field.png"))); // NOI18N
        getContentPane().add(usernameFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 184, -1, -1));

        rankingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/RankinggButon.png"))); // NOI18N
        getContentPane().add(rankingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 232, -1, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 228, 141, 25));

        passwordFieldLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Username field.png"))); // NOI18N
        getContentPane().add(passwordFieldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 224, -1, -1));

        signUpButon.setBackground(new java.awt.Color(0, 42, 93));
        signUpButon.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        signUpButon.setForeground(new java.awt.Color(255, 255, 255));
        signUpButon.setText("Sign Up");
        signUpButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 315, 105, 24));

        playButon.setBackground(new java.awt.Color(0, 42, 93));
        playButon.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        playButon.setForeground(new java.awt.Color(255, 255, 255));
        playButon.setText("PLAY NOW");
        getContentPane().add(playButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 270, 128, -1));

        playRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Rectangle 4.png"))); // NOI18N
        getContentPane().add(playRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 266, -1, -1));

        quitRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/Rectangle 2.png"))); // NOI18N
        getContentPane().add(quitRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 312, -1, -1));

        aiLaTrieuPhuLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elements/AiLaTrieuPhu.png"))); // NOI18N
        getContentPane().add(aiLaTrieuPhuLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -20, -1, -1));

        welcomeBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/login-bg.png"))); // NOI18N
        getContentPane().add(welcomeBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("File");

        qrCodeItem.setText("bổ sung câu hỏi");
        qrCodeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrCodeItemActionPerformed(evt);
            }
        });
        jMenu1.add(qrCodeItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButonActionPerformed

    private void qrCodeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrCodeItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qrCodeItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }

    public static void display() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }


    private void evenHandler() {

        setLocationRelativeTo(null);
        setDocumentFilter(passwordField,15);
        getRootPane().setDefaultButton(playButon);
//        setLocation(420, 250);
        makeButtonTransparent(rankingButon);

//        PlayAudio.playAudio("C:\\Users\\admin\\IdeaProjects\\AiLaTrieuPhu\\" +
//                "src\\main\\java\\org\\example\\file\\audio\\funky-and-jazzy-gang-loop-251858.wav",-10);
        // Sử dụng JButton thông thường và thay đổi con trỏ chuột
        playButon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        signUpButon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        rankingButon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        //phát âm thanh khi di chuyển chuột đến
        rankingButon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-3-269281.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-3-269281.wav"));
            }

        });
        playButon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-3-269281.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-3-269281.wav"));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {

//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-off-269284.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-off-269284.wav"));
            }
        });
        signUpButon.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                PlayAudio.playAudio("src/main/java/org/example/file/audio/pop-3-269281.wav");
                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-3-269281.wav"));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {

                PlayAudioURL.playAudio(getClass().getResource("/audio/pop-off-269284.wav"));
            }
        });

        signUpButon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                SignUpFrame.main(null);
            }
        });
        playButon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (passwordField.getText().isEmpty() || usernameField.getText().isEmpty()) {
                    PlayAudioURL.wrongSound();
                    JOptionPane.showMessageDialog(null, "Nhập đầy đủ username và password!");
                }
                else if(usernameField.getText().contains(" ")){
                    PlayAudioURL.wrongSound();
                    JOptionPane.showMessageDialog(null, "Username không được chứa dấu cách!");
                }
                else if(passwordField.getText().length()<6){
                    PlayAudioURL.wrongSound();
                    JOptionPane.showMessageDialog(null, "Password phải có ít nhất 6 ký tự");
                }
                    else {
                    username = usernameField.getText();
                    password = passwordField.getText();
                    try {
                        player = authService.login(username, password);
                    } catch (Exception ex) {
                        throw new RuntimeException(ex);
                    }
                    if (player != null) {
                        player = playerService.findByUsername(username);
                        System.out.println("ksjfkdj");
                        System.out.println(player.getAvatarPath());
                        if (player.getAvatarPath().isEmpty()) {
                            System.out.println(1);
                            SelectAvatarFrame.display(player, 1, null);
                            PlayAudioURL.stopAudio(clipStart);
//                        PlayAudio.playAudio("src/main/java/org/example/file/audio/level-up-2-199574_1.wav");
                            PlayAudioURL.playAudio(getClass().getResource("/audio/level-up-2-199574_1.wav"));
                        } else {
                            System.out.println(2);
                            PlayAudioURL.stopAudio(clipStart);
//                        PlayAudio.playAudio("src/main/java/org/example/file/audio/level-up-2-199574_1.wav");
                            PlayAudioURL.playAudio(getClass().getResource("/audio/level-up-2-199574_1.wav"));
//                            GameFrame.display(player);
                            ModeSelectionFrame.display(player);
                        }
                        dispose();
                    }
                    else {
                        PlayAudioURL.wrongSound();
                        JOptionPane.showMessageDialog(null, "Username hoặc mật password không chính xác");
                    }

                }
            }
        });
        rankingButon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                PlayAudioURL.playPopOnAudio();
                RankingFrame.display();
            }
        });
        qrCodeItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null,"",
                        "Vào link để thêm câu hỏi",
                        JOptionPane.INFORMATION_MESSAGE,
//                        new ImageIcon("src/main/resources/elements/QRcode-ggSheets.png")
                        new ImageIcon(getClass().getResource("/elements/QRcode-ggSheets.png"))
                );
            }
        });

    }

    static void makeButtonTransparent(JButton button) {
        button.setContentAreaFilled(false);
        button.setOpaque(false);
    }

    public static void setDocumentFilter(JTextField textField, int maxLength) {
        PlainDocument doc = new PlainDocument();
        doc.setDocumentFilter(new javax.swing.text.DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (fb.getDocument().getLength() + string.length() <= maxLength) {
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                if (fb.getDocument().getLength() - length + text.length() <= maxLength) {
                    super.replace(fb, offset, length, text, attrs);
                }
            }
        });
        textField.setDocument(doc);
    }

    private String username;
    private String password;
    private PlayerModel player;
    private PlayerService playerService;
    private AuthService authService;
    private Clip clipStart;
    private Clip clip;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiLaTrieuPhuLable;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordFieldLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton playButon;
    private javax.swing.JLabel playRectangle;
    private javax.swing.JMenuItem qrCodeItem;
    private javax.swing.JLabel quitRectangle;
    private javax.swing.JButton rankingButon;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JButton signUpButon;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameFieldLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeBackground;
    // End of variables declaration//GEN-END:variables
}
